dist: trusty
sudo: false

language: cpp
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libxml-xpath-perl
      - libboost-all-dev
      - omniorb
      - omniidl
      - omniorb-nameserver
      - libomniorb4-dev
      - pkg-config

env:
  global:
    - EXTRA_CMAKE_ARGS="-DENABLE_TESTS=ON -DENABLE_CORBA=ON -DCORBA_IMPLEMENTATION=OMNIORB"
    - BOOST_TEST_LOG_LEVEL=message
  matrix:
    - CXXFLAGS="-std=c++03 -Wall -Wextra -Wno-unused-parameter" CFLAGS="-std=c99 -Wall -Wextra -Wno-unused-parameter"
    - CXXFLAGS="-std=c++11 -Wall -Wextra -Wno-unused-parameter" CFLAGS="-std=c99 -Wall -Wextra -Wno-unused-parameter"


install:
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$(pwd)/install $EXTRA_CMAKE_ARGS
  - make -j2 install

script:
  # Run tests
  - make -j1 check
